global:
  scrape_interval: 10s # How often to scrape targets

scrape_configs:
  # Job 1: Tell Prometheus to monitor itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Job 2: Tell Prometheus to monitor cAdvisor
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]